apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simple-nodejs-be.fullname" . }}
  labels:
    {{- include "simple-nodejs-be.labels" . | nindent 4 }}
data:
  private_key: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFB
    QUFBQ21GbGN6STFOaTFqZEhJQUFBQUdZbU55ZVhCMEFBQUFHQUFBQUJBak5JWnV1bgp4Z0xrTThL
    dXpmbVF1UkFBQUFFQUFBQUFFQUFBR1hBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCZ1FEZTNB
    bDBFTVB6CnV0Vk5rNURpeGFZckdNSzU2UnFVb3FHQmlua2U2U1dWV21xb20xbEJjSld6b3I2SGxu
    TVJQUHI3WUNFc0pLTDRJcHVWd3UKaW5SYTVrZHROVHlNN3l5UVRTUjJ4WENTMGZVSXROdXE4cFVr
    dHNIOFZVZ2dwTWVldzhoSnY3ckZBN3RuSWczVVhDbDZpRgpPTFpLYkRBNWFhMjRpZHBjRDhiMUk5
    L1J6VE9CMWZ1MG9mNXhkOXZnT0R6R3c1SnZIUVNKMEZhQTQyYU5CTUd3ckRoREIzCnNnblJOZFdm
    Nk5OSWg4S3BYWE1LSkFEZjNrbHN5bjZIZThMMmJQTXA4YTR3d3lzMllCMzVwNXpRMEpVUm92c2Rl
    d2xPeEgKTlQ3ZVAxOWVWZjRkQ3JlaWJ4VW1SVWFvYjVERW9IRWs4V3J4aktXSVlVdUxlRDZBZmNX
    Nm9YeVJVMll5OFZydDZTcUZsNQpXQWk0N1ZNRlRrRFpZUy9lQ3ZHNTNxOVVCSHBDajdRdmIwdlNr
    Q1pYQnZCSWhsdzE5M0YzUFg0V3ZPMUlYc013dlExRDFYCmxtb21zSXRicU0wY0p5S3c2TFUxOFFX
    aUJIdkU3QnFjcGhhb0w1RTA4VzJBVFRTUklNQ3A2cnQ0cnB0TTdLeUdLOHJjNlcKVVlyQ25XdDZL
    bENBOEFBQVdRWGsrbFZ4NmJINWl0SUtLWW1RcjZjUi81eHRaMkdIQXhuWXR2bFczeG5HaFUwTUh2
    K2xKMgp1b1dsVDJSWEU1cGRNVVFqN3JOV0FNcWt3aWZTS1pzOXdCZlllbzFUYUZEbUMzblc3eUhT
    TjNYVHVPNzhtUElXNUp5dm1FClJqNXFqc1VuN2ZObXpFQ29BeG5WRVJod25GM0txVUJFUHpJQWM2
    Lzd2L25hOU5UaWlHYUpQY285bHZDb1BXYlZMTjA4V0cKU3V5VSsweDV6YzNlYnp1UGNZcXU1L2M1
    bm1pR3hoQUxySWhqSVMwT1YxbXRBQUZodmRNak1JSE9pak96U0tWQ0M3clJrNQprRzlFTUxOdk9u
    L0RVVlNSSGFtdzVnczJWM1YrWnEyZzVuWVdmZ3E4YURTVEI4WGxJek9qMWN6M0h3Zk42cGZTTlEv
    M1FlCndPUWZXZlRXZE8rSlNMOGFvQk41V2c4dERiZ212bWJGcklOc0pmRmZTbTB3WmdjSGhDN1Vs
    NFUzdjRjOFBvTmRLOUhYd2kKVEtLeko5bnhMWWIrdkRoNTBjbmtzZXUyZ3QwS3dWcGpJb3J4RXFl
    Szc1NW1LUGFvM0ptT01yNnVGVFFzYitnK1pOZ1B3bApuUkhBNElneCt6QURGajN0d2xkbktJaVJw
    QlE1SjRhY3VyM3VRK3NhYW5CVFhndWwxVGlGaVVHVDJjbnorSWlDc2RQb3ZnClRBTXQ4NjhXNUxt
    enBmSDRDeTU0SnRhUkM0L1V1TW5rVEdiV2d1dFZEbldqMnN0T0F6c1ExWW1oSDVpZ1VtYzk0bVVM
    K1cKOHZRRENLcGVJOG4rcXVEUzl6eFR2eTRMNEg1SXo3T1psaDBoNk4xM0JEdkNZWEtjTkYvdWdr
    ZnhaYnU4bVpzWlFRelhOUgp3T3JFdEtvSGM0QW5YWU56c3VIRW9FeUx5SnhHZkZSRFNUTGJ5Tjl3
    Rk9TL2MwazlHanRlK2tRUlpqQlZHT1JFNXNONlgzCmFrVW5URjc2UmhiRWMrTGFtcndNMWg1MzQw
    Yndvc1JiUjhJK1Vyc1FkRmZKQkVqMVpTeU1SSmxNa0ZVTmk2Ymx0N2JoeXgKZWErUG0yQTYxNG5s
    WVVCancyS0t6em44Ti8wSDJOcEpqSXB0dkRzYnJ4M0JTL3JLd09lSndhdlJyR25JbEV6dUFhZzR2
    eApaYjJUUFZ0YTQ1dXo3ZlFQNUlCbDgzYjBCSktJNVp2L2ZuaVVlTEk3OFcvVXNacWI2NFlRYmZS
    eUJ6RnRJMVQvU3NDaTBCCmUwRXlLTXpieHRTY2VUMU1iOGVKaVZJcTA0WHB3ZXo5ZklVdDVyU2Vk
    WkQ4S1BxOFA2czBjR3NSN1FtdzZlWFovZEJSL2EKczV2UGhmSVVtUWF3bW53QVZ1V05SZFFRNzlq
    VUJTbjVNK1pSVlZUZ0VHK3ZGeXZ4ci9iWnFPbzFKQ29xNUJtUWhMV0dSSgpEazlUb2xiZUZJVkZy
    a3VYa2N1OTlhMDc5dXg3WFNrT042NG9QekhyY3NFempQQTFHUHFzOUNHQlNPMTZ3cS9uSTN6ZytF
    CmtjT0NhdXJjOXlISkpQd2R1ZW0wKzhXTFgzV29HTmZRUkt1cnRRemUycHB5OEthckV0RGhEZDk2
    c0traFlhcU9nM0dPWDgKWXg4MjdMNHZ1V1NKU0lxS3VPMmtINmtPQ01VTk8xNnBpdjB6Lzh1M0NK
    eE9HaDkrNEZaSW9wODFmaUZUS0xoVjMvZ3dMbQpmekZZKytLSVpyTGZaY1VqemQ4ME5ORWphNjlG
    NDUyRWI5SHJJNUJ1ck4vUHpuREVpOWJ6TTU5OFk3YmV5bDQva2Q0UjJlClM3U1c5L0xPckd3NVVn
    eHRpVStrVjhuUHoxUGRneE80c1Jsbm50U0JFd2tRQnpNa0xPcHEyaDJCdUoyVGxNUC9UV3V3TFEK
    c0RrdjFZazFwRDByb0dtdE16YnVqblVSR3hxUko4Z1VtdUlvdDRocGZ5UlNzc3ZuUlFRWjNsUUNR
    Q3dIaUUrSEp4WFdmNQpjNTh6T01qVzdvMjF0SThlMTN1VW5iUm9RVkpNOVhZcWsxdXNQWElrWVBZ
    TDl1T3czQVcvWm4rY25EcnNYdlRLOVp4Z0dECi85MGIxQk53VnFNbFVLK1FnZ0hOd2w1cUQ4ZW9Y
    SzVjRHZhdjY2dGUrRStWN0ZZRlEwNnczdHl0UlZ6OFNqb2FpQ2hOMDIKbXVJanZsNkc3SG9qMWhP
    Yk0ydC9aaGVOMUVTaFMxMXo4NjhoaFM2TXg3R3ZJZHRrWHV2ZGlCWU1pQkxPc2hKUXhCOE16eApp
    dWc5VytEaTN1cExmMFVNQzFUcUFER3Boc0lIUlU3UmJtSFE4UndwN2RvZ3N3bURmcFJTYXBQdDlw
    MEQrNkFkNVZCemkzCmYzQlBYajc2VUJMTUVKQ3JaUjFQMjh2bkFBN0F5TkhhTHZNUGxXRE1HNXYz
    Vi9VVit1Z3lGY29CQU95amlRZ1lTVDhGM2UKSHg3VVBWbFRLOGR5dmsxWitZdzBucmZOQ2xJPQot
    LS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0=
